### ISSUE TITLE
Writing text in the Surname field is automatically copied to the Your job position field

### ISSUE THREAD

**Issue by tmszi** [auto-mat/ride-to-work-by-bike-frontend#211]
**Describe the bug**
Writing text in the 'Surname' field is automatically copied to the 'Your job position' field.

**To Reproduce**

1. Check the rendered page URL https://rtwbb-test.dopracenakole.net/#/register-coordinator
2.  Try to write some text into **Surname** field
3.  Same text is showed in **Your job title** field

**Expected behavior**
Writing text in the 'Surname' field should not be automatically copied to the 'Your job position' field.

**Screenshots**

<img src="https://github.com/auto-mat/ride-to-work-by-bike-frontend/assets/50632337/0aee03ad-8960-408d-851e-836e1c8c2bdd" width="380" height="380"/>

**System description:**

- Operating System: all

**Comment by maceksimon** [comment]
@tmszi fixed in PR #214
